# Generated by Django 3.1 on 2021-03-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('estados', models.CharField(choices=[(0, 'Abierto'), (1, 'Pendiente'), (2, 'En Proceso'), (3, 'Resuelto'), (4, 'Cerrado')], max_length=100, verbose_name='Estados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
